### PR TITLE
Fix/ Add support for floats to parseNumberField

### PR DESCRIPTION
**Pull request by haroldrubio**
This PR uses a regex to match the first number of a field and parse it as either a float or an integer

### CODE REVIEW

**Comment by zbialecki** [comment]
Where is this used? Can you give some steps to test it?

**Comment by haroldrubio** [comment]
You can go to the EACL 2024 PC console on the live site to see some examples and compare them to this branch, here is an example of a before and after:
beforeChange
afterChange

**Comment by melisabok** [comment]
How is the value stored in the note?

**Comment by haroldrubio** [comment]
I see, the EACL data was posted using the old enum format using only strings, it looks like data with type float using an enum of objects renders correctly. We can close this PR in that case

**Comment by zbialecki** [comment]
Yes, let's go with using an enum of objects then. Thanks for checking that.

**Pull request closed without merging**
