### PR TITLE
Fix/ AC Console - remove hardcoded role names

### PR DESCRIPTION
**Pull request by xkopenreview**
this pr should remove hardcode role names from AC console

### CODE REVIEW

**Review by enrubio — COMMENTED** [review]
I get this error when trying to access the Senior Program Committee console, I'm unsure if this is a problem with UI changes or the AAAI tests?
Screenshot 2024-05-07 at 4 22 10 PM

**Comment by melisabok** [comment]
Xukun fixed it here: https://github.com/openreview/openreview-py/pull/2128

Is your branch up to date?

**Review by enrubio — COMMENTED** [review]
A few things I noticed - The AC console still shows "Show/Hide reviewers" and "Show Reviewer Activity":
Screenshot 2024-05-07 at 5 42 20 PM

The reviewer activity modal shows "Paper 1 Reviewer [anon ID] Activity":
Screenshot 2024-05-07 at 5 51 23 PM

When sending messages as a Senior PC, this modal isn't correctly showing who the emails are being sent to. The number (14) is correct and emails are sent correctly, but I'd expect it to show:
```
Program Committee AAAIOne <****@aaai.org> x4
Program Committee AAAITwo <****@aaai.org> x5
Program Committee AAAIThree <****@aaai.org> x5
```
Screenshot 2024-05-07 at 6 07 54 PM

**Comment by melisabok** [comment]
> maybe it should group by profile id instead

this is a better approach.

**Comment by melisabok** [comment]
> this is caused by api still using hardcoded role names and will be updated later so this is a temp issue so no action

isn't there a chance to group by profile id?

**Comment by enrubio** [comment]
> [11dcde8](https://github.com/openreview/openreview-web/pull/1924/commits/11dcde88cfec05696dd5b43ad170a54e51afc510) should fix this
> the changes are shared with pc console and ethics chair console

The PC and AC console look good with the changes:
AC_Console

I'm not sure how the ethics chair console is affected but I ran it with the AAAI tests and this is what it looks like, I think it looks normal:
Ethics_Chair_Console

@xkopenreview one small thing - since we're replacing "review" everywhere, maybe this text in the activity modal should also be updated:
Modal

**Review by zbialecki — APPROVED** [review]

**Review by enrubio — APPROVED** [review]
Tested this again with the API changes and everything looks good.

**Pull request merged**
