### PR TITLE
Feature/ User moderation - allow a short note to be saved with impersonated ids in the past

### PR DESCRIPTION
**Pull request by xkopenreview**
this pr should allow a short note to be added when impersonating a user
so that purpose of past impersonations is clear and the impersonate link can be reused

### CODE REVIEW

**Review by emily-grabowski — APPROVED** [review]
Looks like this is working as expected. Are the notes visible to other support team members? Will we also be able to see the notes of PCs who impersonate authors?

**Comment by emily-grabowski** [comment]
Ok thanks for clarifying!

**Review by racheljsmart — APPROVED** [review]

**Comment by racheljsmart** [comment]
If impersonating the same user multiple times, the note is overwritten each time. It's not really an issue, just the observed behavior.

**Review by enrubio — APPROVED** [review]
Changes look good.

**Pull request merged**
