### PR TITLE
Fix/SAC console - remove hardcoded role names

### PR DESCRIPTION
**Pull request by xkopenreview**
this pr should remove hardcoded role names from sac console

### CODE REVIEW

**Comment by enrubio** [comment]
that would be great, thanks Xukun!

**Comment by enrubio** [comment]
I highlighted a few places in the SAC console that need to be updated:

SAC console Submission Status tab:
Screenshot 2024-05-30 at 12 59 15 PM

Capitalization in Query Search modal for Paper Status tab used in SAC & PC console:
QuerySearchPaperStatus

Everything else looks good, SPC Status tab:
Screenshot 2024-05-30 at 1 02 53 PM

Tasks tab:
Screenshot 2024-05-30 at 1 02 58 PM

**Comment by enrubio** [comment]
Oohh okay I'll check.

I also noticed as an AC sending messages to PCs (SACs to Reviewers), the message modal correctly shows the number of emails and who they're sent to. But this was an issue in [#1924  ](https://github.com/openreview/openreview-web/pull/1924#pullrequestreview-2044290300) for some reason, so maybe an API change is not needed? What do you think @xkopenreview?

Screenshot 2024-05-30 at 1 15 47 PM

**Comment by enrubio** [comment]
@xkopenreview Discussed with @melisabok and decided that the SAC console tests will be added in a separate PR. Right now the plan is to:
1. Test again & merge #1924. I believe we'll make a quick fix in the API to fix the email grouping issue. 
2. Review this PR again & merge it. 
3. Merge [openreview-py#2109](https://github.com/openreview/openreview-py/pull/2109) which will add `seniorAreaChairName` to the PC console webfields.

**Review by melisabok — APPROVED** [review]

**Comment by enrubio** [comment]
I didn't end up adding any fields to the missingconfigs of the SAC or PC console, but I removed `officialMetaReviewName` in the missingconfig of the PC console since I added a default value.

**Review by enrubio — APPROVED** [review]
Looks like everything is working as expected.

**Pull request merged**
